package core

import (
	"fmt"
	"path/filepath"
	"strings"
)

// GetDefaultPromptTemplate returns the iteration prompt template content.
// This prompt is fed to the AI tool on each loop iteration, instructing it
// to select a task, implement it, run quality checks, and commit.
func GetDefaultPromptTemplate() string {
	return `# Autonomous Iteration Prompt

You are running in autonomous mode as part of the Ralph Wiggum methodology.
Each iteration is independent — you start with a fresh context window.

## Context Efficiency

Your context window is limited. Minimize token consumption so you have room to implement:

1. **Read ` + "`.claude/auto/task-context.md`" + ` FIRST** — it contains your assigned task with
   full detail (ID, title, description, files to modify). Do NOT read the full prd.json
   to find your task.
2. **Read ` + "`.claude/auto/progress-context.md`" + `** for learnings from prior iterations.
3. **Read only the files listed in ` + "`files_to_modify`" + `** for your task. Do NOT explore
   the broader codebase unless the task specifically requires understanding dependencies.
4. **Update prd.json directly** for status changes — you already know the task ID from
   task-context.md.
5. **Read ` + "`CLAUDE.md`" + ` only if needed** — the key project guardrails are:
   functions ≤50 lines, files ≤300 lines, tests required, conventional commits.

## Your Task

1. **Read task context** (small, pre-computed files):
   - Read ` + "`.claude/auto/task-context.md`" + ` — contains your assigned task detail
   - Read ` + "`.claude/auto/progress-context.md`" + ` — learnings from prior iterations
   - Read ` + "`CLAUDE.md`" + ` or ` + "`AGENTS.md`" + ` only if you need project-specific guardrails

2. **Implement the task**:
   - Update the task's status to "in_progress" in prd.json
   - Read only the files listed in ` + "`files_to_modify`" + ` from task-context.md
   - Follow project guardrails
   - Write tests alongside code
   - Keep changes atomic — one task per iteration

3. **Run quality checks**:
   - Execute the commands listed in ` + "`prd.json`" + ` under ` + "`config.quality_checks`" + `
   - All checks must pass before committing
   - If a check fails, fix the issue and retry

4. **Commit changes**:
   - Use conventional commit format: ` + "`type(scope): description`" + `
   - Include task ID in commit message
   - Example: ` + "`feat(auth): task 1.1 - create user schema`" + `

5. **Update state**:
   - Set the task's status to "completed" in prd.json
   - Record the commit SHA in the task's ` + "`commit_sha`" + ` field
   - Update ` + "`progress.total_tasks`" + ` and ` + "`progress.completed_tasks`" + `

6. **Document learnings**:
   - Append any insights, gotchas, or decisions to ` + "`.claude/auto/progress.md`" + ` (full history log)
   - Format: ` + "`[timestamp] [iteration:N] [task:ID] LEARNING: description`" + `

## Rules

- Complete exactly ONE task per iteration
- Never skip quality checks
- If stuck for too long, mark the task as "blocked" and document why
- Keep functions ≤50 lines, files ≤300 lines (project guardrails)
- All exported functions need documentation
- Write tests for all new code

## Error Recovery

If you encounter errors:
1. Try to fix them within this iteration
2. If unfixable, mark the task as "blocked" with a description
3. Append the error details to progress.md as a LEARNING entry
4. The next iteration will have fresh context and can try a different approach
`
}

// GeneratePromptFile generates the prompt.md content customized for a project
func GeneratePromptFile(config AutoConfig) string {
	var sb strings.Builder
	sb.WriteString(GetDefaultPromptTemplate())
	sb.WriteString("\n## Project-Specific Configuration\n\n")

	fmt.Fprintf(&sb, "- **AI Tool**: %s\n", config.AITool)
	fmt.Fprintf(&sb, "- **Max Iterations**: %d\n", config.MaxIterations)
	fmt.Fprintf(&sb, "- **PRD File**: %s\n", filepath.Join(AutoDir, AutoPRDFile))
	fmt.Fprintf(&sb, "- **Progress File**: %s\n", filepath.Join(AutoDir, AutoProgressFile))

	if len(config.QualityChecks) > 0 {
		sb.WriteString("\n### Quality Checks\n\n")
		sb.WriteString("Run these commands as quality gates before committing:\n\n")
		sb.WriteString("```bash\n")
		for _, check := range config.QualityChecks {
			sb.WriteString(check + "\n")
		}
		sb.WriteString("```\n")
	}

	if config.PilotMode {
		sb.WriteString("\n## Pilot Mode Note\n\n")
		sb.WriteString("This loop is running in **pilot mode** — tasks were auto-discovered.\n")
		sb.WriteString("Tasks may have been generated by a discovery iteration, not a human.\n")
		sb.WriteString("If a task seems unclear or risky, mark it as \"blocked\" with a note.\n")
	}

	return sb.String()
}
